zuul:
  routes:
    project_management:
      sensitiveHeaders:
      path: /api/project/**
      serviceId: PROJECT_MANAGEMENT
    auth-server:
      path: /api/auth/**
      serviceId: AUTH-SERVER
spring.application.name: zuul_server
eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/
zuul.decodeUrl: false
server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true
